Feat/header
curator-OEUVRE/OEUVRE-client pull request #7
Opened 2022-09-30 18:24 UTC by yuda1124

> 해당 PR이 어떤 PR인지에 대한 간략한 설명을 추가합니다.
- header 컴포넌트 구현
- SafeArea 로직 추가

## 체크리스트

> 작성자, 리뷰어 모두가 확인해야할 사항들 입니다.
- [ ] 코드를 실행했을 때 잘 동작하는 코드인지 확인
- [ ] 작성한 코드에 대해 모두 이해하였는지 확인
- [ ] 관련된 label 추가했는지 확인

## 관련 이슈

> 이 PR이 머지되었을 때 closed될 이슈의 번호를 지정합니다.
- resolve #6  

## 설명
아직 react-navigation이 추가되지 않아서 마크업만 구현했습니다!
추가되면 다음에 navigation.pop 추가하면 될 거 같아요!
headerRight를 optional props로 받을 수 있도록 구현했습니다.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/18456572/193332817-73b2448e-5593-4143-b772-b279b13d2cbc.png">
<img width="384" alt="image" src="https://user-images.githubusercontent.com/18456572/193332867-9551c6ee-b8b1-4d6f-8f0a-21d27859d516.png">

2022-10-01 16:06 UTC, aube-dev requested changes

2022-10-01 16:06 UTC, aube-dev commented on src/components/Header.tsx
> +          source={require('@/assets/icons/arrow_back.png')}
🍌 png 말고 svg로 쓰는 게 낫지 않을까요!?

2022-10-01 16:06 UTC, aube-dev commented on src/components/Header.tsx
> +    <View style={[styles.container, { marginTop: insets.top }]}>
🍌 이 부분 여기서 처리하지 말고, 그냥 이 `Header`를 쓰는 screen에서 알아서 `SafeArea` 처리를 하는 게 낫지 않을까요? 어차피 `SafeAreaView`를 감싸는 건 screen에서 관리하는 것이 좀 더 정확한 레이아웃을 보여줄 수 있을 것 같아요! (그런 경우는 당연히 잘 없긴 한데 예를 들어 `Header`가 screen의 맨 위가 아닌 경우에는 `marginTop` 속성 때문에 무조건 불필요한 margin이 생겨버릴 것 같고, 그런 경우를 생각하지 않더라도 어차피 screen에서도 safe area 관련 처리를 할 건데 `Header`에서도 관련 처리를 하는 건 관심사가 중복되는 것 같고 헷갈릴 수 있을 것 같아요!)

```typescript
const SomeScreen = () => (
  <SafeAreaView>
    <Header />
  </SafeAreaView>
);
```

2022-10-02 06:44 UTC, yuda1124 commented on src/components/Header.tsx
> +  headerRight?: () => React.ReactNode;
props로 컴포넌트를 전달하는 방식이 어떤 방식이 좋을까 고민하다가 "component as a Function" pattern을 사용하기로 결정해서 이렇게 수정했습니다.

아래 글을 참고 했구요 (https://www.developerway.com/posts/react-component-as-prop-the-right-way)
짧게 요약하자면
1. "component as an Element" pattern ex) <Button icon={<Icon /> />
미리 정해진 위치에 전달 받는 컴포넌트 측에서 props를 변경할 필요가 없을 때 사용
2. "component as a Component" pattern ex) <Button icon={Icon} />
전달 받는 컴포넌트 측에서 주로 props를 통해 컴포넌트를 수정하거나 customise할 니즈가 있을 때 사용
3. "component as a Function" pattern ex) <Button renderIcon={(props) => <Icon {...{props}}/>} />
전달 하는 컴포넌트 측에서 state에 맞춰 function의 결과를 수정하고 싶을 때 사용

지금의 디자인에서는 3개 중 어떤 방식을 사용하더라도 구현에 문제가 없는 상황이지만
추후 확장성을 고려했을 때 1번보다 2, 3번이 낫겠다는 생각이 들어서 수정했습니다.
2, 3번 중에 3번을 선택한 이유는 headerTitle이나 headerRight는 Header컴포넌트보다 Header컴포넌트를 가지고 있는 host 컴포넌트 상태에 따라서 render 결과가 달라지는게 맞다고 생각해 3번을 선택했구요!

제가 설명을 잘 못하는 편이긴 한데... 혹시 궁금하시거나 의견이 있으시면 알려주세요!!

2022-10-03 14:11 UTC, aube-dev approved these changes
LGTM 👍

2022-10-03 14:25 UTC, merged